server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/juhard"
    username: root
    password: Anhhung98@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true